variable "primary_database" {}
variable "resource_group" {}
variable "location" {}
variable "primary_database_version" {}
variable "primary_database_admin" {}
variable "primary_database_password" {}
variable "secondary_database" {}
variable "secondary_database_version" {}
variable "secondary_database_admin" {}
variable "secondary_password" {}
